Repository MohamedBeydoun/atlas, pull requests merged in 2020-02, with the labels that each got.

#1 Features/init
  .gitignore
  LICENSE
  README.md
  cmd/root.go
  go.mod
  go.sum
  main.go
Labels: enhancement

#2 Features/create command
  Makefile
  cmd/create.go
  cmd/root.go
  pkg/prj/create.go
  pkg/prj/create_test.go
  pkg/testdata/.gitignore.golden
  pkg/testdata/README.md.golden
  pkg/testdata/app.ts.golden
  pkg/testdata/package.json.golden
  pkg/testdata/server.ts.golden
  pkg/testdata/tsconfig.json.golden
  pkg/testdata/tslint.json.golden
  pkg/tpl/create.go
  pkg/util/golden.go
Labels: enhancement

#3 Features/generate model command
  cmd/create.go
  cmd/generate.go
  cmd/model.go
  cmd/root.go
  pkg/generator/model.go
  pkg/generator/model_test.go
  pkg/prj/create.go
  pkg/prj/create_test.go
  pkg/prj/util.go
  pkg/testdata/server.ts.golden
  pkg/testdata/src/app.ts.golden
  pkg/testdata/src/database/interactions/test.ts.golden
  pkg/testdata/src/database/models/test.ts.golden
  pkg/testdata/src/interfaces/ITest.ts.golden
  pkg/testdata/src/server.ts.golden
  pkg/tpl/model.go
  pkg/tpl/project.go
  pkg/util/file.go
Labels: enhancement

#6 Bugfixes/typos
  pkg/prj/create.go
  pkg/prj/create_test.go
  pkg/testdata/src/server.ts.golden
  pkg/tpl/model.go
  pkg/util/file.go
Labels: enhancement

#7 Made versioning script and updated readme
  .gitignore
  Makefile
  README.md
  scripts/version.sh
Labels: documentation, enhancement

#8 Fixed spacing bugs in readme
  README.md
Labels: documentation, enhancement

#25 Any case in name will now become camelcase
  README.md
  cmd/controller.go
  cmd/model.go
  cmd/router.go
  go.mod
  go.sum
  pkg/tpl/model.go
Labels: bug

#26 Bugfixes/illegal symbols in resource flags
  cmd/controller.go
  cmd/model.go
  cmd/router.go
  go.sum
Labels: bug

#27 Bugfixes/prompt before overwrite
  pkg/generator/controller.go
  pkg/generator/model.go
  pkg/generator/router.go
  pkg/util/userinput.go
Labels: bug

#28 Bugfixes/update files with router generator
  README.md
  pkg/generator/router.go
Labels: bug
